- name: Instalar PHP-FPM y extensiones
  apt:
    name:
      - php-fpm
      - php-mysql
      - php-mbstring
      - php-cli
      - nfs-common
    state: present
    update_cache: yes

- name: Configurar PHP-FPM para escuchar en TCP
  lineinfile:
    path: /etc/php/8.4/fpm/pool.d/www.conf
    regexp: '^listen ='
    line: 'listen = 0.0.0.0:9000'
  notify: restart php-fpm

- name: Crear DocumentRoot si no existe
  ansible.builtin.file:
    path: "/{{ item.datos.documentroot }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  loop: "{{ virtualhosts }}"

- name: AÃ±adir entrada en fstab y montar NFS
  ansible.posix.mount:
    src: "10.0.0.4:/var/www/javier"
    path: "/var/www/javier"
    fstype: nfs
    opts: "rw,_netdev"
    state: mounted
