network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true
      nameservers:
    ens4: 
      dhcp4: false
      addresses: ["192.168.201.2/24"]
      nameservers:
        addresses: [8.8.8.8]
    ens5: 
      dhcp4: false
      addresses: ["10.0.0.2/24"]
