- name: Instalar Apache y utilidades
  apt:
    name:
      - apache2
      - git
      - php-mbstring
      - php-mysql
      - libapache2-mod-fcgid
      - nfs-common
    state: present
    update_cache: yes


- name: Activar módulos de Apache para PHP-FPM remoto
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop:
    - proxy
    - proxy_fcgi
    - setenvif
  notify: restart apache2


- name: Configuración de virtualhost
  template: 
    src: etc/apache2/vhost.j2
    dest: /etc/apache2/sites-available/{{ item.name }}.conf
    owner: root
    group: root
  loop: "{{ virtualhosts }}"
  notify: restart apache2


- name: Crear DocumentRoot si no existe
  ansible.builtin.file:
    path: "/{{ item.datos.documentroot }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  loop: "{{ virtualhosts }}"


- name: Activar VirtualHosts
  file:
    src: /etc/apache2/sites-available/{{ item.name }}.conf
    dest: /etc/apache2/sites-enabled/{{ item.name }}.conf
    state: link
  loop: "{{ virtualhosts }}"
  notify: restart apache2

- name: Añadir entrada en fstab y montar NFS
  ansible.posix.mount:
    src: "10.0.0.4:/var/www/javier"
    path: "/var/www/javier"
    fstype: nfs
    opts: "rw,_netdev"
    state: mounted
